import React from "react";
import { Text } from "@/components/ui/text";
import { useUser } from "@/context/profileContext";
import { StyleSheet, useWindowDimensions } from "react-native";
import keyframes from "react-native-reanimated/lib/typescript/css/stylesheet/keyframes";

// import { useState } from "react";

type appMessageProp = {
  userId: string | undefined;
};

export default function AppMessage({ userId }: appMessageProp) {

    const { profiles } = useUser();
    const myProfile = profiles?.find((p) => p.uid === userId);
    const profileNickname = myProfile?.nickName;
    const dimensions = useWindowDimensions()
    const isLargeScreen = dimensions.width >= 1280 // computer UI condition
    const isMediumScreen = dimensions.width <= 1280 && dimensions.width > 768 // tablet UI condition

    const styles = StyleSheet.create({
    MessageFont: {
        fontSize: isLargeScreen || isMediumScreen ? 24 : 14, 
        color: "white", 
        fontWeight: isLargeScreen || isMediumScreen ? "900" : "bold" , 
        fontFamily: "roboto,",
    },
    messageAnimation: {
        width: "100%",
        flexWrap: "nowrap",
    },
});



    const messageText = {
        m1: `hello ${profileNickname}! welcome back`,
        m2: `${profileNickname}, relax ka muna, di ka hinahabol.`,
        m3: `${profileNickname}, tubig ka muna bago ka ma-dehydrate.`,
        m4: `${profileNickname}, kalma, hindi pa tapos lahat.`,
        m5: `${profileNickname}, huminga ka naman minsan.`,
        m6: `${profileNickname}, coffee ka na? mukhang kailangan mo.`,
        m7: `${profileNickname}, wag kang nerbyoso, cute ka naman.`,
        m8: `${profileNickname}, slow down, buhay ay di karera.`,
        m9: `${profileNickname}, keep Going!`,
        m10: `${profileNickname}, chillax.`,
        m11: `${profileNickname}, wag ka mag-stress, ako na bahala, jwk.`,
        m12: `${profileNickname}, pwede kang tumayo, kung gusto mo.`,
        m13: `${profileNickname}, easy lang, hindi tatakbo yung deadline.`,
        m14: `${profileNickname}, relax, di ka naman sinisingil.`,
        m15: `${profileNickname}, wag ka masyadong seryoso, di bagay.`,
        m16: `${profileNickname}, live in present`,
        m17: `${profileNickname}, kapuy? but you're doing great`,
        m18: `${profileNickname}, Good day!.`,
        m19: `${profileNickname}, smile ka naman, while music is playing.`,
        m20: `Wag panic ${profileNickname}, kaya yan.`,
        m21: `${profileNickname}, breathe in, breathe out… char.`,
        m22: `${profileNickname}, tubig lang katapat niyan.`,
        m23: ` hindi ka robot ${profileNickname}, magpahinga ka.`,
        m24: `${profileNickname}, parang mag ta-transform kana ah.`,
        m25: `${profileNickname}, bakit ang cute mo ngayon?`,
        m26: `${profileNickname}, be cheerfull.`,
        m27: `${profileNickname}, teka lang, naglo-load pa data ko.`,
        m28: `${profileNickname}, can't wait for lunch.`,
        m29: `${profileNickname}, Taposin na natin to.`,
        m30: `${profileNickname}, kumusta ka dyan baka kausapin muna yung code.`,
        m31: `${profileNickname}, lumabas ka naman minsan, vitamin D.`,
        m32: `${profileNickname}, the north remembers.`,
        m33: `gutom ka na ${profileNickname}? tara kain.`,
        m34: `${profileNickname}, kaya pa? tara!`,
        m35: `${profileNickname}, cute mo pag stressed.`,
        m36: `${profileNickname}, be grateful.`,
        m37: `Kaya ko to`,
        m38: `Tell you're self to be Positive.`,
        m39: `${profileNickname}, mahirap mag code pag gutom.`,
        m40: `${profileNickname}, be positive.`,
        m41: `${profileNickname}, Manifesting.`,
        m42: `${profileNickname}, pwede ka na magpahinga.`,
        m43: `${profileNickname}, don't worry, be happy.`,
        m44: `${profileNickname}, never mag worry.`,
        m45: `${profileNickname}, hoy, uminom ka ng tubig.`,
        m46: `I'm craving for some ice-cream.`,
        m47: `Sige, ubosin natin lahat nang task.`,
        m48: `${profileNickname}, normal lang ma pagud, kaya mag pahinga muna`,
        m49: `${profileNickname}, lakas ng energy mo ah.`,
        m50: `${profileNickname}, ?`,
        m51: `${profileNickname}, chill buddy, buhay pa tayo.`,
        m52: `${profileNickname}, wag ka malungkot, cute ka naman.`,
        m53: `${profileNickname}, laban lang HUHUHU.`,
        m54: `${profileNickname}, wag mo problemahin yung di ka naman mahal—char.`,
        m55: `${profileNickname}, okay ka lang da?`,
        m56: `${profileNickname}, kalma ka lang, hindi kita iiwan.`,
        m57: `${profileNickname}, pwede ka magbreak, hindi ka machine.`,
        m58: `${profileNickname}, ang seryoso mo, napapraning ako.`,
        m59: `${profileNickname}, magfanaw-fanaw na ako, bye.`,
        m60: `${profileNickname}, huwag ka magmadali, di mawawala yung mundo.`,
        m61: `${profileNickname}, chillax lang parang wala bukas.`,
        m62: `${profileNickname}, bakit parang ikaw may kasalanan?`,
        m63: `${profileNickname}, smile.`,
        m64: `${profileNickname}, pahinga ka muna, ang sipag mo eh.`,
        m65: `${profileNickname}, wag ka overthink, pangit yan.`,
        m66: `${profileNickname}, oy, relax ka lang.`,
        m67: `stay focused ${profileNickname}.`,
        m68: `Padayon lang, bisag lisod—kay sa unahan, naa gyud kalampusan para nimo.`,
        m69: `${profileNickname}, Padayon lang, kay kaya ra nimo.`,
        m70: `${profileNickname}, when life give you lemon, take it.`,
        m71: `${profileNickname}, Ayaw undang; duol na ang kalampusan.`,
        m72: `${profileNickname}, Bisan hinay, basta kanunay.`,
        m73: `${profileNickname}, Sigeg lihok, sigeg uswag.`,
        m74: `Gahi ug ulo para sa damgo, dili sa problema.`,
        m75: `${profileNickname}, Gamay’g progreso, progreso gihapon.`,
        m76: `${profileNickname}, Ayaw kabalaka, maayo ra ang dagan sa panahon.`,
        m77: `${profileNickname}, Laban lang, way atras.`,
        m78: `${profileNickname}, Ang tawo nga maningkamot, moani gyud.`,
        m79: `${profileNickname}, magpahinga ka, para di ka ma-bad trip.`,
        m80: `${profileNickname}, uy, pa-cute ka nanaman.`,
        m81: `${profileNickname}, Gahi ka, mas gahi pa sa pagsulay.`,
        m82: `${profileNickname}, Abanti pirmi, bisan gagmay.`,
        m83: `${profileNickname}, Sul-ob ang kusog, biyae ang kahadlok.`,
        m84: `${profileNickname}, Ang damgo, padulngan—not balibaran.`,
        m85: `${profileNickname}, Simula karon, padulong sa mas maayo.`,
        m86: `${profileNickname}, Nakakapoy? Pahuway gamay, pero ayaw undang.`,
        m87: `${profileNickname}, Kugi karon, harvest ugma.`,
        m88: `Imong kaugalingon ang pinaka-kusgan nimo’ng puslanan.`,
        m89: `${profileNickname}, Dili kinahanglan dali, kinahanglan padayon.`,
        m90: `${profileNickname}, Ayaw kompara sa uban; lahi kag agi.`,
        m91: `Gubot ang kalibutan pero klaro imong padulngan.`,
        m92: `${profileNickname}, Namugnaw ang adlaw, pero init imong paglaum.`,
        m93: `${profileNickname}, wag mo masyado dibdibin, magaan lang yan.`,
        m94: `${profileNickname}, chill ka, may reward yan.`,
        m95: `${profileNickname}, Lamig sa Office.`,
        m96: `${profileNickname}, Sa tanang butang, salig sa imong abilidad.`,
        m97: `${profileNickname}, Sulayi hangtod molampos.`,
        m98: `${profileNickname}, Ayaw kahadlok mangandoy ug dako.`,
        m99: `${profileNickname}, relax ka muna, lab u.`,
        m100: `${profileNickname}, Kalma lang, kaya ra nimo.`,
        m101: `You ready ${profileNickname}! Lets Go!`,
        m102: `Hoping you a good day ${profileNickname}.`,
        m103: `Focus ka lang ${profileNickname}!`,
        m104: `Kaya muna ${profileNickname}, Fighting!`,
        m105: `Ready kana ${profileNickname}? Ano palag na?`,
        m106: `${profileNickname}? Never Kapuyon.`,
        m108: `Let's go! Let's go ${profileNickname}!`,
        m107: `Sarap mo ${profileNickname}!`,
        m109: `Here we go again ${profileNickname}! let's work`,
        m110: `let's finnish this ${profileNickname}!`,
        m111: `${profileNickname}! Kape muna.`,
        m112: `Pagud kana ${profileNickname}? mag C2 ka.`,
        m113: `${profileNickname}, chill lang.`,
        m114: `Never give up never back down.`,
        m115: `${profileNickname}, you got this.`,
        m116: `${profileNickname}, keep going.`,
        m117: `${profileNickname}, small steps count.`,
        m118: `${profileNickname}, progress is progress.`,
        m119: `${profileNickname}, believe in yourself.`,
        m120: `${profileNickname}, don’t stop now.`,
        m121: `${profileNickname}, you're getting better.`,
        m122: `${profileNickname}, stay focused.`,
        m123: `${profileNickname}, keep pushing.`,
        m124: `${profileNickname}, you’re stronger than you think.`,
        m125: `${profileNickname}, one day at a time.`,
        m126: `${profileNickname}, trust the process.`,
        m127: `${profileNickname}, keep your head up.`,
        m128: `${profileNickname}, you’re doing great.`,
        m129: `${profileNickname}, don't underestimate yourself.`,
        m130: `${profileNickname}, keep moving forward.`,
        m131: `${profileNickname}, you’re closer than you think.`,
        m132: `${profileNickname}, you can handle this.`,
        m133: `${profileNickname}, stay positive.`,
        m134: `${profileNickname}, proud of you already.`,
        m135: `${profileNickname}, Ayaw pasagdi ang damgo nga lipay ka.`,
        m136: `${profileNickname}, Ayaw surrender; sugod nasad.`,
        m137: `finally, nandito kana ${profileNickname}. Tara kape.`,
        m138: `Amoyin mo ang hangin ${profileNickname}`,
        m139: `${profileNickname}, Pangandoy ug maayo; paningkamot ug maayo.`,
        m140: `Hi ${profileNickname}!`,
        m141: `Never say never.`,
        m142: `Hello there! ${profileNickname}`,
        m143: `Good day! ${profileNickname}`,
        m144: `Hey, nice to see you!`,
        m145: `Hi ${profileNickname}, how’s everything?`,
        m146: `What’s up ${profileNickname}?`,
        m147: `Yo ${profileNickname}!`,
        m148: `Greetings ${profileNickname}!`,
        m149: `Hello, friend!`,
        m150: `let's get ready to rumble.`,
        m151: `Hiya!`,
        m152: `Long time no see!`,
        m153: `Good to have you back ${profileNickname}!`,
        m154: `Howdy!`,
        m155: `Hey ${profileNickname}, you’re looking great today!`,
        m156: `Hi ${profileNickname}, hope you're doing well!`,
        m157: `Nice to meet you!`,
        m158: `Pleasure seeing you again ${profileNickname}!`,
        m159: `Hey there, superstar!`,
        m160: `Warm greetings ${profileNickname}!`,
        m161: `Hi ${profileNickname}, ready to start the day?`,
        m162: `Good morning, ${profileNickname}!`,
        m163: `Rise and shine, ${profileNickname}!`,
        m164: `${profileNickname}, let's make today awesome!`,
        m165: `Hey ${profileNickname}, glad you're here!`,
        m166: `Welcome back, legend ${profileNickname}!`,
        m167: `Top of the day to you, ${profileNickname}!`,
        m168: `Hey ${profileNickname}, feeling motivated?`,
        m169: `${profileNickname}, let’s conquer the day!`,
        m170: `Hello again, ${profileNickname}!`,
        m171: `Great to see you, ${profileNickname}!`,
        m172: `Welcome, ${profileNickname}! Let's begin.`,
        m173: `Hi ${profileNickname}, ready for action?`,
        m174: `Yo ${profileNickname}! Padayon lang, kaya ra jud nimo.`,
        m175: `Hey ${profileNickname}, sugdi ang adlaw nga puno'g kusog!`,
        m176: `Yo ${profileNickname}, lig-ona imong kasing-kasing karon.`,
        m177: `${profileNickname}, balik nasad? Laban ta!`,
        m178: `Nisulod na si ${profileNickname}—ready na para mulampos.`,
        m179: `${profileNickname}, hinay-hinay pero siguradong abante.`,
        m180: `Sup ${profileNickname}? Let’s give today your best shot.`,
        m181: `${profileNickname}, andam na mosugod ug maayo nga adlaw?`,
        m182: `Oh wow, ni-appear si ${profileNickname}! Padayon ta.`,
        m183: `${profileNickname}, mosulod murag boss—kaya kaayo.`,
        m184: `Hey ${profileNickname}, buhata ang imong makaya karon.`,
        m185: `${profileNickname}, mas maayo ning adlaw karon—salig lang.`,
        m186: `Nia na si ${profileNickname}, ang tawo nga dili mo-undang.`,
        m187: `Welcome back ${profileNickname}—kampante mi sa imong kusog.`,
        m188: `${profileNickname}, ayaw kabalaka—sakto imong agi.`,
        m189: `${profileNickname}, andam nasad para sa paningkamot.`,
        m190: `Hi ${profileNickname}—padayon ug barog lig-on.`,
        m191: `${profileNickname}, kalma lang, kaya ra nimo tanan.`,
        m192: `Oh look, si ${profileNickname}, punô’g paglaum.`,
        m193: `${profileNickname}, andam ka modaug sa adlaw? Kaya kaayo.`,
        m194: `Hey ${profileNickname}, atong himoon nga malinaw ang adlaw.`,
        m195: `${profileNickname}, disiplinado ta karon—laban!`,
        m196: `${profileNickname}, maayo kay nakabalik ka. Abante napud.`,
        m197: `Yo ${profileNickname}, ayaw pagduha-duha—kaya nimo.`,
        m198: `${profileNickname}, bisan unsa pa’y agi, padayon gihapon.`,
        m199: `${profileNickname}, hinaut nga nindot ang dagan sa imong adlaw.`,
        m200: `${profileNickname}, welcome—salig lang sa imong kusog.`,
        m201: `${profileNickname}, padayon dev—one commit at a time.`,
        m202: `${profileNickname}, hinay-hinay pero sure—just like clean code.`,
        m203: `${profileNickname}, abante lang; bugs are part of the journey.`,
        m204: `Let’s go ${profileNickname}! Sulbadon ra nato ni.`,
        m205: `${profileNickname}, breathe lang—di na ka first time nag-debug.`,
        m206: `${profileNickname}, keep pushing; ang success murag PR approval.`,
        m207: `Nice to see you ${profileNickname}! Larga na pud ta sa tasks.`,
        m208: `${profileNickname}, focus lang—parehas sa git diff.`,
        m209: `${profileNickname}, kaya ra nimo bisan daghan tickets.`,
        m210: `Let's go ${profileNickname}, smooth ra ning adlaw karon.`,
        m211: `${profileNickname}, one line of progress is still progress.`,
        m212: `${profileNickname}, likayi ang stress—embrace the process.`,
        m213: `Good day ${profileNickname}! Padayon sa imong craft.`,
        m214: `${profileNickname}, ikaw ang developer nga dili mo-give up.`,
        m215: `${profileNickname}, ayaw kabalaka—tanang bug masulbad.`,
        m216: `${profileNickname}, lihok lang; greatness takes time.`,
        m217: `Yo ${profileNickname}, consistent lang sa code and life.`,
        m218: `${profileNickname}, maayo ka—ayaw duda sa imong skill.`,
        m219: `${profileNickname}, today is another chance to improve.`,
        m220: `${profileNickname}, padayon; deadlines come and go.`,
        m221: `${profileNickname}, kusog kaayo kag potential.`,
        m222: `Let’s get it ${profileNickname}! Shine today.`,
        m223: `${profileNickname}, trabaho lang, dreams later. Bitaw—both.`,
        m224: `${profileNickname}, imong kusog mas bright pa sa IDE.`,
        m225: `${profileNickname}, hinumdumi—dili shortcut ang success.`,
        m226: `Let's code ${profileNickname}! Smooth ra kaayo ka.`,
        m227: `${profileNickname}, maayo ka mu-adjust; dev ka ba.`,
        m228: `Stay solid ${profileNickname}, ikaw ang backbone sa team.`,
        m229: `${profileNickname}, klaro kaayo imong direction—forward.`,
        m230: `${profileNickname}, bisan kapoy, mo-sulod gihapon. Respect.`,
        m231: `Good job ${profileNickname}, padayon pa.`,
        m232: `${profileNickname}, imong progress dili sayon pero worth it.`,
        m233: `Keep going ${profileNickname}! We're proud of you.`,
        m234: `${profileNickname}, walay task nga di nimo kaya.`,
        m235: `${profileNickname}, bisag kapila ka mag-refactor—padayon.`,
        m236: `Hello ${profileNickname}, today we build, we grow.`,
        m237: `${profileNickname}, ang imong effort dili mawala.`,
        m238: `${profileNickname}, trust the process—like version control.`,
        m239: `Let’s grind ${profileNickname}, nindot ang output unya.`,
        m240: `${profileNickname}, ikaw ang type nga employee nga mo-lampos.`,
        m241: `${profileNickname}, yaw ka give up, ikaw ang main dev.`,
        m242: `Keep steady ${profileNickname}, lisod pero kaya.`,
        m243: `${profileNickname}, igang ang motivation—let’s code.`,
        m244: `${profileNickname}, ikaw ang hero sa imong own project.`,
        m245: `Hi ${profileNickname}, everyday is upgrade day.`,
        m246: `${profileNickname}, limitless imong growth.`,
        m247: `Go go ${profileNickname}, ang future bright pa sa light mode.`,
        m248: `${profileNickname}, kanunay kag mo-level up.`,
        m249: `${profileNickname}, salig lang sa imong abilidad.`,
        m250: `${profileNickname}, let's conquer this sprint—laban kaayo.`,


    };

    const keys = Object.keys(messageText) as Array<keyof typeof messageText>;
    const messageKeys = Math.floor(Math.random() * keys.length);
    const randomMessage = messageText[keys[messageKeys]] ?? "";


    return (
        <>
            <Text style={{...styles.MessageFont, ...styles.messageAnimation}}>{randomMessage}</Text>
        </>
    );
}




